#!/bin/bash
set -ex

# Optional checkout revision, or default to grpc master
TARGET_REV=${1:-master}

# Prepping the folder
rm -rf tmp && mkdir tmp

### Clone grpc and extract shallow source copy
git clone https://github.com/grpc/grpc.git tmp
pushd tmp
git checkout $TARGET_REV
REVISION=$(git rev-parse HEAD)
git submodule update --init

# Extract source files for gRPC ios
python ../scripts/extract-grpc-ios-files.py build_handwritten.yaml build_autogenerated.yaml
popd

sed -i".bak" -E -e 's=https://github.com/grpc/grpc.git=https://github.com/grpc/grpc-ios.git=g' *.podspec
rm -f *.podspec.bak

rm -rf tmp
