source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '9.0'

GRPC_PODSPEC_ROOT = '../../..'

target 'gRPCSample' do
  use_frameworks!
  pod 'gRPC-ProtoRPC',  :path => GRPC_PODSPEC_ROOT
  pod 'gRPC', :path => GRPC_PODSPEC_ROOT
  pod 'gRPC-RxLibrary', :path => GRPC_PODSPEC_ROOT
end
