source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '15.0'

install! 'cocoapods', :deterministic_uuids => false

GRPC_PODSPEC_ROOT = '../../..'

target 'gRPCSample' do
  pod 'gRPC-ProtoRPC',  :path => GRPC_PODSPEC_ROOT
  pod 'gRPC', :path => GRPC_PODSPEC_ROOT
  pod 'gRPC-RxLibrary', :path => GRPC_PODSPEC_ROOT
  pod 'gRPC-Core', :path => GRPC_PODSPEC_ROOT
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['CLANG_CXX_LANGUAGE_STANDARD'] = 'c++17'
    end
  end
end
