name: Cocoapod prod release
on:
  release:
    types: [published]
concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false
env:
  COCOAPODS_TRUNK_TOKEN: ${{ secrets.COCOAPODS_TRUNK_TOKEN }}
  TAG: ${{ github.event.release.tag_name }}
jobs:
  release-cocoapod-gRPC-Core:
    runs-on: macos-12
    steps:
      - name: Repo checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.ref }}

      - name: Prepare environment
        run: scripts/prepare_env.sh

      - name: Pod release
        run: scripts/release_cocoapod.sh gRPC-Core.podspec

      - name: Wait for pod avaialble
        run: |
          version=${TAG#v}
          timeout 1h scripts/wait_for_pod_release.sh gRPC-Core $version
  release-cocoapod-gRPC-Cpp:
    runs-on: macos-12
    needs: [release-cocoapod-gRPC-Core]
    steps:
      - name: Repo checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.ref }}

      - name: Prepare environment
        run: scripts/prepare_env.sh

      - name: Pod release
        run: scripts/release_cocoapod.sh gRPC-C++.podspec

      - name: Wait for pod avaialble
        run: |
          version=${TAG#v}
          timeout 1h scripts/wait_for_pod_release.sh gRPC-C++ $version
  release-cocoapod-gRPC-RxLibrary:
    runs-on: macos-12
    steps:
      - name: Repo checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.ref }}

      - name: Prepare environment
        run: scripts/prepare_env.sh

      - name: Pod release
        run: scripts/release_cocoapod.sh gRPC-RxLibrary.podspec

      - name: Wait for pod avaialble
        run: |
          version=${TAG#v}
          timeout 1h scripts/wait_for_pod_release.sh gRPC-RxLibrary $version

  release-cocoapod-gRPC:
    runs-on: macos-12
    needs: [release-cocoapod-gRPC-RxLibrary, release-cocoapod-gRPC-Core]
    steps:
      - name: Repo checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.ref }}

      - name: Prepare environment
        run: scripts/prepare_env.sh

      - name: Pod release
        run: scripts/release_cocoapod.sh gRPC.podspec

      - name: Wait for pod avaialble
        run: |
          version=${TAG#v}
          timeout 1h scripts/wait_for_pod_release.sh gRPC $version

  release-cocoapod-gRPC-ProtoRPC:
    runs-on: macos-12
    needs: [release-cocoapod-gRPC-RxLibrary, release-cocoapod-gRPC]
    steps:
      - name: Repo checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.ref }}

      - name: Prepare environment
        run: scripts/prepare_env.sh

      - name: Pod release
        run: scripts/release_cocoapod.sh gRPC-ProtoRPC.podspec

      - name: Wait for pod avaialble
        run: |
          version=${TAG#v}
          timeout 1h scripts/wait_for_pod_release.sh gRPC-ProtoRPC $version
